### ISSUE TITLE
consider enum class

### ISSUE THREAD

**Issue by svorobiev** [istudyatuni/tictactoe-terminal#10]
https://github.com/istudyatuni/tictactoe-terminal/blob/b9da06aef942766a4a2e289eb92830276da7f274/include/tictactoe.h#L16

**Comment by istudyatuni** [comment]
also didn't understand

**Comment by svorobiev** [comment]
In cpp11 you can declare like this:

enum class foo {
Value1,
Value2
};

And then use like this:

if (value == foo::Value1) {
Logic
}

Enum class values don't decay to ints also. Google enum class c++11

**Comment by istudyatuni** [comment]
Wow. It's cool
