### ISSUE TITLE
your locals and member variables are undistinguishable. You want to flag your member varialbles somehow: either prefix them with m_ (m_member) or suffix them with _ (member_)

### ISSUE THREAD

**Issue by svorobiev** [istudyatuni/tictactoe-terminal#5]
https://github.com/istudyatuni/tictactoe-terminal/blob/b9da06aef942766a4a2e289eb92830276da7f274/include/map.h#L9

**Comment by istudyatuni** [comment]
i used the same name 'player' in class members and `bool Tictactoe::win_right_now(char player, char opponent)`, but gcc helped me)
