### ISSUE TITLE
ptotected means your class's descendants can mess with your members. Typically in production code you only make destructors protected, and very rarely so (long story why)

### ISSUE THREAD

**Issue by svorobiev** [istudyatuni/tictactoe-terminal#6]
https://github.com/istudyatuni/tictactoe-terminal/blob/b9da06aef942766a4a2e289eb92830276da7f274/include/map.h#L13

**Comment by istudyatuni** [comment]
make public instead protected? or add functions get, set for work with private members?

**Comment by svorobiev** [comment]
It is a complicated thing. Making member vars protected in production code means that reader has to investigate the whole inheritance hierarchy to see how they are manipulated. The whole purpose of private/protected is to avoid misuse of class. The standard modern approach is, if you have a class invariant, it shall stand if a class object is used with a public interface. Protected is a leaking abstraction

**Comment by svorobiev** [comment]
Now, why did I bring up dtors. Consider you have a base class where you have nontrivial ownership management. In that case you want class's descendants to have access to store, but noone else

**Comment by istudyatuni** [comment]
It was difficult but it seems i understood
