### ISSUE TITLE
indent

### ISSUE THREAD

**Issue by svorobiev** [istudyatuni/tictactoe-terminal#8]
https://github.com/istudyatuni/tictactoe-terminal/blob/b9da06aef942766a4a2e289eb92830276da7f274/include/tictactoe.h#L9

**Comment by istudyatuni** [comment]
in more details, please

**Comment by istudyatuni** [comment]
Check again, I corrected a little

**Comment by svorobiev** [comment]
Public Map should be on same line as class. Delete the line break
